export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const QUESTIONS_FAIL = "QUESTIONS_FAIL";
export const QUESTIONS_LOADING = "QUESTIONS_LOADING";
export const LOAD_QUESTIONS = "LOAD_QUESTIONS";
export const LOAD_SINGLE_TASK = "LOAD_SINGLE_TASK";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";
export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";

export const GET_POSTS = "GET_POSTS";
export const GET_SINGLE_POST = "GET_SINGLE_POST";
export const GET_POST_LOADING = "GET_POST_LOADING";
export const GET_POST_FAIL = "GET_POST_FAIL";

export const GET_SENT_QUESTIONS = "GET_SENT_QUESTIONS";

export const SOCKET_CONNECT = "SOCKET_CONNECT";
export const SOCKET_CONNECT_LOADING = "SOCKET_CONNECT_LOADING";
export const SOCKET_CONNECT_FAILED = "SOCKET_CONNECT_FAILED";

export const GET_CHATS = "GET_CHATS";
export const GET_CHATS_LOADING = "GET_CHATS_LOADING";
export const GET_CHATS_FAIL = "GET_CHATS_FAIL";

export const GET_MESSAGES = "GET_MESSAGES";
export const GET_MESSAGES_LOADING = "GET_MESSAGES_LOADING";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";
